services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:5432", "--",
      "python", "/app/porfolio/manage.py", "runserver",
      "0.0.0.0:8000"]
      # "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"
    ports:
      - "8000:8000"  #local : docker
    volumes:
      - .:/app    # every change at . will be reflected on /app (docker app) and vice versa
    depends_on:
      - db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54321:5432

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"