# Generated by Django 5.0.6 on 2024-08-09 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_options_alter_exchange_options_and_more'),
        ('news', '0004_alter_category_options_alter_news_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
