# Generated by Django 5.0.6 on 2024-08-08 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=256)),
                ('image', models.URLField(max_length=2000)),
                ('daily_volume', models.FloatField()),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=7, max_digits=15)),
                ('rank', models.IntegerField()),
                ('daily_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('icon', models.URLField(max_length=1000, null=True)),
                ('market_cap', models.DecimalField(decimal_places=3, max_digits=15)),
                ('twitter', models.URLField(max_length=512)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('users_interested', models.ManyToManyField(related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('exchanges', models.ManyToManyField(related_name='assets', to='asset.exchange')),
            ],
        ),
    ]
