# Generated by Django 5.0.6 on 2024-08-09 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_description_alter_asset_exchanges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-rank']},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['-daily_volume']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchanges',
            field=models.ManyToManyField(related_name='assets', to='asset.exchange'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='users_interested',
            field=models.ManyToManyField(blank=True, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-rank'], name='asset_asset_rank_dc1496_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name', 'symbol'], name='asset_asset_name_7cfb71_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['daily_change'], name='asset_asset_daily_c_c56b34_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['-daily_volume'], name='asset_excha_daily_v_16d616_idx'),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['name'], name='asset_excha_name_54824b_idx'),
        ),
    ]
