# Generated by Django 5.0.6 on 2024-08-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_asset_market_cap_alter_asset_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['rank']},
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='asset_asset_rank_dc1496_idx',
        ),
    ]
