# Generated by Django 5.0.6 on 2024-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchange',
            name='asset_excha_daily_v_16d616_idx',
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['daily_volume'], name='asset_excha_daily_v_13ce4e_idx'),
        ),
    ]
