# Generated by Django 5.0.6 on 2024-08-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_remove_exchange_asset_excha_daily_v_16d616_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='daily_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
