# Generated by Django 5.0.6 on 2024-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_asset_ath_asset_ath_change_percentage_asset_ath_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
