# Generated by Django 5.0.6 on 2024-08-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_asset_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='established',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='trust_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='trust_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
